// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLiSach.Models;

namespace QuanLiSach.Migrations
{
    [DbContext(typeof(Appcontext))]
    [Migration("20201113022954_tr")]
    partial class tr
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("QuanLiSach.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Author")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategorybookId")
                        .HasColumnType("int");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<string>("Despition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Namebook")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Publishingyear")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategorybookId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Dale CarNeGie",
                            CategorybookId = 1,
                            Count = 1,
                            Namebook = "Đắc Nhân Tâm",
                            Publishingyear = 2016
                        },
                        new
                        {
                            Id = 2,
                            Author = "David j.Lieberman",
                            CategorybookId = 2,
                            Count = 2,
                            Namebook = "Đọc Vị Bất Kì Ai",
                            Publishingyear = 2015
                        },
                        new
                        {
                            Id = 3,
                            Author = "Robin Sharma",
                            CategorybookId = 3,
                            Count = 1,
                            Namebook = "Đời Ngắn Đừng Ngủ Dài",
                            Publishingyear = 2017
                        });
                });

            modelBuilder.Entity("QuanLiSach.Models.CategoryBook", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CategoryBooks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Sách Giáo Trình"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Sách Tiểu Thuyết"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Sách Tâm Lý"
                        });
                });

            modelBuilder.Entity("QuanLiSach.Models.Book", b =>
                {
                    b.HasOne("QuanLiSach.Models.CategoryBook", "categoryBook")
                        .WithMany("Books")
                        .HasForeignKey("CategorybookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("categoryBook");
                });

            modelBuilder.Entity("QuanLiSach.Models.CategoryBook", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
